PRESETS = {
    "logo_clean": {
        "art_type": "logo",
        "profile": "engraving",
        "min_area": 10,
        "denoise": 1,
        "close_gaps": 1,
        "simplify": 0.08,
        "preserve_holes": True,
        "preserve_original_paths": True,
        "geometry_strength": 0.0,
        "max_nodes_per_path": 420,
        "remove_border_noise": True,
        "fill_small_holes": False,
        "edge_protection": 0.75,
    },
    "logo_noisy": {
        "art_type": "logo",
        "profile": "engraving",
        "min_area": 22,
        "denoise": 2,
        "close_gaps": 1,
        "simplify": 0.14,
        "preserve_holes": True,
        "preserve_original_paths": True,
        "geometry_strength": 0.0,
        "max_nodes_per_path": 320,
        "remove_border_noise": True,
        "fill_small_holes": True,
        "edge_protection": 0.55,
    },
    "technical": {
        "art_type": "technical",
        "profile": "cut",
        "min_area": 12,
        "denoise": 1,
        "close_gaps": 1,
        "simplify": 0.10,
        "preserve_holes": True,
        "preserve_original_paths": False,
        "geometry_strength": 0.80,
        "max_nodes_per_path": 220,
        "remove_border_noise": True,
        "fill_small_holes": False,
        "edge_protection": 0.65,
    },
}
